version: "2"
services:
  web:
    build: 
      context: .
      dockerfile: web.Dockerfile
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    links:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - 27017:27017
#    volumes:
#      - ./mongodb/db:/data/db




 