# NodeJS App
web:
 image: node:alpine
 container_name: api-nodejs
 working_dir: /home/node/app
 ports:
  - 3000:3000
 environment:
  - NODE_ENV=production
 volumes:
  - ./:/home/node/app
 links:
  - mongodb
 command: npm start


# MongoDB
mongodb:
 image: mongo
 container_name: api-mongodb
 ports:
  - 27017:27017
 volumes:
  - mongodb-data:/data/db