version: "2"
services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - 80:80
      - 443:443
    links:
      - web
    volumes:
      - $HOME/.caddy:/root/.caddy
  web:
    build: 
      context: .
      dockerfile: web.Dockerfile
    ports:
      - 3000:3000
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/db:/data/db




 