version: "2"
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    links:
      - mongo
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db




 